ALTER TABLE STOCK_MOVEMENT --addition of the foreign key
    ADD FOREIGN KEY (ID_PRODUCT)
        REFERENCES PRODUCT (IDPRODUCT);

ALTER TABLE SALE --correction of the word 'PENDING'
    CHANGE STATUS_SALE
        STATUS_SALE ENUM("PENDING","COMPLETED", "CANCELED") NOT NULL;