ALTER TABLE STOCK_MOVEMENT
    ADD FOREIGN KEY (ID_PRODUCT)
        REFERENCES PRODUCT (IDPRODUCT);

ALTER TABLE SALE
    CHANGE STATUS_SALE
        STATUS_SALE ENUM("PENDING","COMPLETED", "CANCELED") NOT NULL;